spring:
  application:
    name: bilibili-eureka-ha
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

---

spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1

---

spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2