server:
  port: 9002
spring:
  application:
    name: bilibili-upload-processor
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ZUIEWANGGUAN
    # 139.159.134.136:3306
    url: jdbc:mysql://localhost:3306/bilibili?characterEncoding=utf-8&useSSL=false
    # Hikari是Spring Boot 2.0之后默认整合的数据库连接池，比druid更快的数据库连接池
    #数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: BilibiliHikariPool
      # 连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 12
      # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      # 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000
      # 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #连接测试查询
      connection-test-query: SELECT 1
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:

  servlet:
    multipart:
      max-file-size: 500Mb
      max-request-size: 500Mb
  rabbitmq:
    host: 192.168.202.167
    port: 5672
    username: guest
    password: guest
    virtual-host: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true

FFMPEG_PATH: D:/FFmpeg/bin/ffmpeg.exe
m3u8folder_path: D:/WebStormWorkSpace/哔哩哔哩/bilibili-Nuxt/static/source/hls/
upload:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video


